name: 'Impersonate A GitHub App'
description: Retrieve an App Installation Token to allow Actions to impersonate a GitHub App.
author: Hamel Husain
inputs:
  APP_PEM:
    description: string version of your PEM file used to authenticate as a GitHub App
    required: false
  APP_ID:
    description: you GITHUB App ID.
    required: false
outputs:
  APP_INSTALLATION_TOKEN:
    description: The installation access token for the GitHub App corresponding to and the current repository.
branding:
  color: 'orange'
  icon: 'users'
runs:
  using: 'docker'
  image: 'docker://hamelsmu/actions-impersonate'